recipe: default.v1

assistant_id: 20251106-152117-easy-tie

language: en

pipeline:
  - name: components.whitespace_filter.WhitespaceFilter
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: "/tmp"
    pooling: "mean"
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    random_seed: 42
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 40
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.7
#    core_fallback_action_name: "action_default_fallback"
    core_fallback_action_name: "action_query_rag"
    enable_fallback_prediction: true
    ambiguity_threshold: 0.1
  - name: TEDPolicy
    epochs: 100
    max_history: 5
    core_fallback_threshold: 0.3
    constrain_similarities: true
